<a href="https://colab.research.google.com/github/sgl13/Natural_Language_Processing/blob/main/Spam_Ham_Classification_Using_BOW_And_TF_IDF_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BOW,TFIDF,Machine Learning Algorithms

1.Preprocessing And Cleaning

2.Train Test Split

3.BOW And TF-IDF (Sentences--->vectors) {Preventing Data Leakage}

4.Trained Our Models

In [1]:
import pandas as pd
messages=pd.read_csv('/content/SMSSpamCollection',
                    sep='\t',names=["label","message"])

In [2]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [3]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [5]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [6]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

Create Bag Of Words

In [7]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [8]:
## independent features
X=cv.fit_transform(corpus).toarray()

In [9]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [10]:
cv.vocabulary_

{'go': np.int64(819),
 'point': np.int64(1629),
 'crazi': np.int64(457),
 'avail': np.int64(123),
 'bugi': np.int64(234),
 'great': np.int64(867),
 'world': np.int64(2420),
 'la': np.int64(1104),
 'cine': np.int64(356),
 'got': np.int64(858),
 'wat': np.int64(2324),
 'ok': np.int64(1476),
 'lar': np.int64(1117),
 'joke': np.int64(1062),
 'wif': np.int64(2376),
 'oni': np.int64(1498),
 'ok lar': np.int64(1479),
 'free': np.int64(746),
 'entri': np.int64(623),
 'wkli': np.int64(2403),
 'comp': np.int64(407),
 'win': np.int64(2381),
 'cup': np.int64(472),
 'final': np.int64(703),
 'st': np.int64(1964),
 'may': np.int64(1272),
 'text': np.int64(2087),
 'receiv': np.int64(1714),
 'question': np.int64(1683),
 'std': np.int64(1980),
 'txt': np.int64(2200),
 'rate': np.int64(1695),
 'appli': np.int64(87),
 'free entri': np.int64(752),
 'entri wkli': np.int64(625),
 'wkli comp': np.int64(2404),
 'std txt': np.int64(1981),
 'txt rate': np.int64(2206),
 'rate appli': np.int64(1696),
 'dun': np.in

In [11]:
## Output Features
y=pd.get_dummies(messages['label'])

In [12]:
y=y.iloc[:,0].values

In [13]:
y.shape

(5572,)

In [14]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

Create Bag Of Words

In [15]:
## Output Features
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [16]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [17]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [18]:
len(X_train),len(y_train)

(4457, 4457)

In [19]:
## independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [20]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [21]:
cv.vocabulary_

{'cheer': np.int64(343),
 'messag': np.int64(1311),
 'phone': np.int64(1582),
 'age': np.int64(34),
 'decid': np.int64(523),
 'whether': np.int64(2395),
 'text': np.int64(2094),
 'dunno': np.int64(599),
 'ask': np.int64(108),
 'lol': np.int64(1206),
 'mom': np.int64(1358),
 'take': np.int64(2061),
 'forev': np.int64(727),
 'like': np.int64(1176),
 'minut': np.int64(1328),
 'away': np.int64(136),
 'ugh': np.int64(2225),
 'import': np.int64(1019),
 'custom': np.int64(485),
 'servic': np.int64(1860),
 'announc': np.int64(68),
 'call': np.int64(252),
 'freephon': np.int64(756),
 'import custom': np.int64(1020),
 'custom servic': np.int64(487),
 'servic announc': np.int64(1861),
 'call freephon': np.int64(260),
 'thanx': np.int64(2111),
 'darlin': np.int64(500),
 'im': np.int64(1014),
 'cool': np.int64(443),
 'bday': np.int64(161),
 'drink': np.int64(589),
 'nite': np.int64(1449),
 'morrow': np.int64(1374),
 'care': np.int64(303),
 'soon': np.int64(1954),
 'xxx': np.int64(2466),
 'darlin im

In [22]:
from sklearn.naive_bayes import MultinomialNB

In [23]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [24]:
y_pred=spam_detect_model.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score,classification_report

In [26]:
accuracy_score(y_test,y_pred)

0.9856502242152466

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.96      0.92      0.94       145
        True       0.99      0.99      0.99       970

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



Creating The TF-IDF Model

In [28]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [30]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [31]:
tv.vocabulary_

{'go': np.int64(815),
 'buy': np.int64(239),
 'mum': np.int64(1392),
 'present': np.int64(1637),
 'ar': np.int64(89),
 'go buy': np.int64(819),
 'ya': np.int64(2461),
 'tel': np.int64(2073),
 'wat': np.int64(2334),
 'ur': np.int64(2246),
 'problem': np.int64(1657),
 'wat ur': np.int64(2338),
 'tick': np.int64(2124),
 'could': np.int64(448),
 'die': np.int64(540),
 'know': np.int64(1103),
 'feet': np.int64(700),
 'need': np.int64(1412),
 'tick tick': np.int64(2125),
 'song': np.int64(1933),
 'free': np.int64(742),
 'top': np.int64(2170),
 'tone': np.int64(2161),
 'call': np.int64(250),
 'nation': np.int64(1404),
 'rate': np.int64(1683),
 'get': np.int64(794),
 'sent': np.int64(1840),
 'everi': np.int64(651),
 'week': np.int64(2356),
 'text': np.int64(2087),
 'per': np.int64(1557),
 'unsub': np.int64(2238),
 'nation rate': np.int64(1405),
 'everi week': np.int64(653),
 'hmv': np.int64(959),
 'bonu': np.int64(198),
 'special': np.int64(1953),
 'pound': np.int64(1625),
 'voucher': np.int64

In [32]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [33]:
#prediction
y_pred=spam_tfidf_model.predict(X_test)

In [34]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9748878923766816


In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.82      0.99      0.89       120
        True       1.00      0.97      0.99       995

    accuracy                           0.97      1115
   macro avg       0.91      0.98      0.94      1115
weighted avg       0.98      0.97      0.98      1115

